//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoaderApiAndAdmin.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> TransportOwnerId { get; set; }
        public string OrderPickup { get; set; }
        public string OrderDropOff { get; set; }
        public string OrderComodity { get; set; }
        public string OrderWeight { get; set; }
        public Nullable<System.DateTime> OrderPickUpDate { get; set; }
        public string OrderLength { get; set; }
        public string OrderWidth { get; set; }
        public string OrderHeight { get; set; }
        public string OrderReceiverName { get; set; }
        public string OrderReceiverCompanyName { get; set; }
        public string OrderAdditionalDetails { get; set; }
        public string OrderStatus { get; set; }
        public string OrderBudget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
